config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users, only: [:index, :show]
  resources :students, only: [:index, :show]
  resources :classrooms, only: [:index, :show]
  resources :majors, only: [:index, :show]
  resources :subjects, only: [:index, :show]
  resources :courses, only: [:index, :show]
  resources :lecturers, only: [:index, :show]

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :subject
  belongs_to :lecturer
  has_many :classroom_students
  has_many :students, through: :classroom_students
end

app/models/classroom_student.rb
class ClassroomStudent < ActiveRecord::Base
  belongs_to :classroom
  belongs_to :student
end

app/models/course.rb
class Course < ActiveRecord::Base
  validates :name, presence: true
  has_many :subjects
  has_many :enrollments
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :student
  belongs_to :course
end

app/models/lecturer.rb
class Lecturer < ActiveRecord::Base
  belongs_to :user
end

app/models/major.rb
class Major < ActiveRecord::Base
  has_many :students
end

app/models/mark.rb
class Mark < ActiveRecord::Base
  belongs_to :student
  belongs_to :subject
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  has_many :classroom_students
  has_many :classrooms, through: :classroom_students
  has_many :marks
  has_many :subjects, through: :marks
  belongs_to :major
  validates :grade_point_average, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 4}
  has_many :enrollments
  has_many :courses, through: :enrollments
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :course
  has_many :marks
  has_many :students, through: :marks
  validates :name, presence: true
  validates :credits, presence: true,
    numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 15}
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  has_secure_password
  enum role: [:manager, :admin]

  def remember
    self.remember_token = User.new_token
    update_attributes! remember_digest: User.digest(remember_token)
  end

  def forget
    update_attributes remember_digest: nil
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
end

app/controllers/majors_controller.rb
class MajorsController < ApplicationController
  def index
    @majors = Major.all
  end

  def show
    @major = Major.find params[:id]
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @q = Student.search(params[:q])
    @students = @q.result(distinct: true)
  end

  def show
    @student = Student.find params[:id]
    @classrooms = @student.classrooms
    @subjects = @student.subjects
    @courses = @student.courses
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/lecturers_helper.rb
module LecturersHelper
end

app/helpers/majors_helper.rb
module MajorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by id: user_id
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by id: user_id
      if user && user.authenticate?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    forget current_user
    session.delete :user_id
    current_user = nil
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end

  def current_user? user
    user == current_user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/students/_search_form.html.erb
<%= search_form_for @q do |f| %>

  <%= f.label :grade_point_average_cont %>
  <%= f.search_field :grade_point_average_cont %>

  <%= f.submit %>
<% end %>

app/views/students/_student_info.html.erb
<div class="row">
  <div class="col-md-4">
    <h4><b>Email:</b></h4>
    <h4><b>Grade point average:</b></h4>
    <h4><b>Major:</b></h4>
    <h4><b>Date of Joining:</b></h4>
  </div>
  <div class="col-md-8">
    <h4><%= @student.user.email %></h4>
    <h4><%= @student.grade_point_average %></h4>
    <h4>
      <%=link_to @student.major.name, major_path(@student.major) unless @student.major.nil? %>
    </h4>
    <h4><%= @student.date_of_joining %></h4>
  </div>
</div>

app/views/students/index.html.erb
<h1>Students</h1>
<%= render "search_form" %>
<table class="table table-bordered table-hover">
  <tr>
    <th>Name</th>
    <th>Date of Birth</th>
    <th>Date of Joining</th>
    <th>Major</th>
    <th>Email</th>
  </tr>
  <% @students.each do |student| %>
    <tr data-link= "<%= student_path(student)%>">
      <td><%= student.user.name %></td>

      <td><%= student.date_of_birth %></td>

      <td><%= student.date_of_joining %></td>

      <td><%= student.major.name unless student.major.nil? %></td>

      <td><%= student.user.email %></td>
    </tr>
  <% end %>
</table>

app/views/students/show.html.erb
<% provide :title, @student.user.name %>
<div class="row">
  <div class="col-md-4">
    <%= image_tag "default_avatar", class: "avatar img-responsive img-circle" %>
    <h3><%= @student.user.name %></h3>
  </div>

  <div class="col-md-8">
    <%= render "student_info" %>
  </div>
</div>

<div class="container">
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#courses">Courses</a></li>
    <li><a data-toggle="tab" href="#subjects">Subjects</a></li>
    <li><a data-toggle="tab" href="#classrooms">Classrooms</a></li>
    <li><a data-toggle="tab" href="#info">Info</a></li>
  </ul>

  <div class="tab-content">
    <div id="courses" class="tab-pane fade in active">
      <h3>Courses</h3>
      <table class="table table-bordered table-hover">
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Start Date</th>
          <th>End Date</th>
        </tr>
        <% @courses.each do |course| %>
          <tr data-link= "<%= course_path(course)%>">
            <td><%= course.name %></td>

            <td><%= course.description %></td>

            <td><%= course.enrollments.find_by(student: @student).start_date %></td>

            <td>
              <%= course.enrollments.find_by(student: @student).end_date %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
    <div id="subjects" class="tab-pane fade">
      <h3>Subjects</h3>
      <table class="table table-bordered table-hover">
        <tr>
          <th>Name</th>
          <th>Credits</th>
          <th>Description</th>
          <th>Mark</th>
        </tr>
        <% @subjects.each do |subject| %>
          <tr data-link= "<%= subject_path(subject)%>">
            <td><%= subject.name %></td>

            <td class= "text-right"><%= subject.credits %></td>

            <td><%= subject.description %></td>

            <td><%= subject.marks.find_by(student: @student).value %></td>
          </tr>
        <% end %>
      </table>
    </div>
    <div id="classrooms" class="tab-pane fade">
      <h3>Classrooms</h3>
      <table class="table table-bordered table-hover">
        <tr>
          <th>Name</th>
          <th>Subject</th>
          <th>Lecturer</th>
          <th>Location</th>
          <th>Start Date</th>
          <th>End Date</th>
        </tr>
        <% @classrooms.each do |classroom| %>
          <tr data-link= "<%= classroom_path(classroom)%>">
            <td><%= classroom.name %></td>

            <td><%= classroom.subject.name unless classroom.subject.nil?%></td>

            <td><%= classroom.lecturer.user.name unless classroom.lecturer.nil?%></td>

            <td><%= classroom.location %></td>

            <td><%= classroom.start_date %></td>

            <td><%= classroom.end_date %></td>
          </tr>
        <% end %>
      </table>

    </div>
    <div id="info" class="tab-pane fade">
      <h3>Student information</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
    </div>
  </div>
</div>