config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users, only: [:index, :show]
  resources :students, only: [:index, :show]
  resources :classrooms, only: [:index, :show]
  resources :majors, only: [:index, :show]
  resources :subjects, only: [:index, :show]
  resources :courses, only: [:index, :show]
  resources :lecturers, only: [:index, :show]

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :subject
  belongs_to :lecturer
  has_many :classroom_students
  has_many :students, through: :classroom_students
end

app/models/classroom_student.rb
class ClassroomStudent < ActiveRecord::Base
  belongs_to :classroom
  belongs_to :student
end

app/models/course.rb
class Course < ActiveRecord::Base
  validates :name, presence: true
  has_many :subjects
  has_many :enrollments
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :student
  belongs_to :course
end

app/models/lecturer.rb
class Lecturer < ActiveRecord::Base
  belongs_to :user
end

app/models/major.rb
class Major < ActiveRecord::Base
  has_many :students
end

app/models/mark.rb
class Mark < ActiveRecord::Base
  belongs_to :student
  belongs_to :subject
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  has_many :classroom_students
  has_many :classrooms, through: :classroom_students
  has_many :marks
  has_many :subjects, through: :marks
  belongs_to :major
  validates :grade_point_average, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 4}
  has_many :enrollments
  has_many :courses, through: :enrollments
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :course
  has_many :marks
  has_many :students, through: :marks
  validates :name, presence: true
  validates :credits, presence: true,
    numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 15}
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  has_secure_password
  enum role: [:manager, :admin]

  def remember
    self.remember_token = User.new_token
    update_attributes! remember_digest: User.digest(remember_token)
  end

  def forget
    update_attributes remember_digest: nil
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
end

app/controllers/lecturers_controller.rb
class LecturersController < ApplicationController
  def index
    @lecturers = Lecturer.all
  end

  def show
    @lecturer = Lecturer.find params[:id]
  end
end

app/controllers/majors_controller.rb
class MajorsController < ApplicationController
  def index
    @majors = Major.all
  end

  def show
    @major = Major.find params[:id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/lecturers_helper.rb
module LecturersHelper
end

app/helpers/majors_helper.rb
module MajorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by id: user_id
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by id: user_id
      if user && user.authenticate?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    forget current_user
    session.delete :user_id
    current_user = nil
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end

  def current_user? user
    user == current_user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lecturers/_lecturer_info.html.erb
<div class="row">
  <div class="col-md-4">
    <h4><b>Email:</b></h4>
    <h4><b>Date of Joining:</b></h4>
    <h4><b>Faculty:</b></h4>
  </div>
  <div class="col-md-8">
    <h4><%= @lecturer.user.email %></h4>
    <h4><%= @lecturer.date_of_joining %></h4>
  </div>
</div>

app/views/lecturers/index.html.erb
<h1>Lecturers</h1>
<table class="table table-bordered table-hover">
  <tr>
    <th>Name</th>
    <th>Date of Birth</th>
    <th>Date of Joining</th>
    <th>Salary ($)</th>
    <th>Email</th>
  </tr>
  <% @lecturers.each do |lecturer| %>
    <tr data-link= "<%= lecturer_path(lecturer)%>">
      <td><%= lecturer.user.name %></td>

      <td><%= lecturer.date_of_birth %></td>

      <td><%= lecturer.date_of_joining %></td>

      <td class="text-right"><%= lecturer.salary %></td>

      <td><%= lecturer.user.email %></td>
    </tr>
  <% end %>
</table>

app/views/lecturers/show.html.erb
<% provide :title, @lecturer.user.name %>
<div class="row">
  <div class="col-md-4">
    <%= image_tag "default_avatar", class: "avatar img-responsive img-circle" %>
    <h3><%= @lecturer.user.name %></h3>
  </div>

  <div class="col-md-8">
    <%= render "lecturer_info" %>
  </div>
</div>