config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users, only: [:index, :show]
  resources :students, only: [:index, :show]
  resources :classrooms, only: [:index, :show]
  resources :majors, only: [:index, :show]
  resources :subjects, only: [:index, :show]
  resources :courses, only: [:index, :show]
  resources :lecturers, only: [:index, :show]

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :subject
  belongs_to :lecturer
  has_many :classroom_students
  has_many :students, through: :classroom_students
end

app/models/classroom_student.rb
class ClassroomStudent < ActiveRecord::Base
  belongs_to :classroom
  belongs_to :student
end

app/models/course.rb
class Course < ActiveRecord::Base
  validates :name, presence: true
  has_many :subjects
  has_many :enrollments
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :student
  belongs_to :course
end

app/models/lecturer.rb
class Lecturer < ActiveRecord::Base
  belongs_to :user
end

app/models/major.rb
class Major < ActiveRecord::Base
  has_many :students
end

app/models/mark.rb
class Mark < ActiveRecord::Base
  belongs_to :student
  belongs_to :subject
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  has_many :classroom_students
  has_many :classrooms, through: :classroom_students
  has_many :marks
  has_many :subjects, through: :marks
  belongs_to :major
  validates :grade_point_average, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 4}
  has_many :enrollments
  has_many :courses, through: :enrollments
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :course
  has_many :marks
  has_many :students, through: :marks
  validates :name, presence: true
  validates :credits, presence: true,
    numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 15}
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  has_secure_password
  enum role: [:manager, :admin]

  def remember
    self.remember_token = User.new_token
    update_attributes! remember_digest: User.digest(remember_token)
  end

  def forget
    update_attributes remember_digest: nil
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/lecturers_helper.rb
module LecturersHelper
end

app/helpers/majors_helper.rb
module MajorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by id: user_id
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by id: user_id
      if user && user.authenticate?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    forget current_user
    session.delete :user_id
    current_user = nil
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end

  def current_user? user
    user == current_user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to t("label_about"), about_path %></li>
      <li><%= link_to t("label_contact"), "#" %></li>
    </ul>
  </nav>
  <div class="bgl"><div class="bgr">
  <a> The System Analysis and Design Assignment </a>
  &copy; by Group 5 - Binh Thanh Nguyen 2015
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to StudentManagementSystem::Info.app_name, root_path, id: "logo", class: "button" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("label_home"), root_path %></li>
        <li><%= link_to t("label.help"), help_path %></li>
          <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= t "label_account" %><b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t("label_profile"), user_path(current_user) %></li>
                <li><%= link_to t("label_settings"), "#" %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to t("label_logout"), logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to t("label_login"), login_path %></li>
          <% end %>
      </ul>
    </nav>
  </div>
  <div class="dropdown", id= "sub-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      Menu<b class="caret"></b>
    </a>
    <ul class="dropdown-menu">

      <li><%= link_to t("label_enroll"), "#{}" %></li>
      <li class="divider"></li>
      <li>
        <%= link_to t("label_report"), "#{}" %>
      </li>
    </ul>
  </div>
  <nav>
    <ul class="nav navbar-nav">
      <li><%= link_to t("label_lecturer_plural"), lecturers_path %></li>
      <li><%= link_to t("label_student_plural"), students_path %></li>
      <li><%= link_to t("label_course_plural"), courses_path %></li>
      <li><%= link_to t("label_subject_plural"), subjects_path %></li>
      <li><%= link_to t("label_classroom_plural"), classrooms_path %></li>
      <li><%= link_to t("label_news"),"#{}" %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= StudentManagementSystem::Info.app_name %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render "layouts/header" %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>